apiVersion: v1
kind: ConfigMap
metadata:
  name: sphinx-plugin-environment
  namespace: kube-system
data:
  environment.coin_api: ""
  environment.coin_local_api: ""
  environment.coin_public_api: ""
  environment.coin_jsonrpc_local_api: ""
  environment.coin_jsonrpc_public_api: ""
  environment.coin_type: ""
  environment.coin_net: ""
  environment.proxy: ""
  environment.sync_interval: ""
  environment.position: ""
  environment.wan_ip: ""
